### ISSUE TITLE
Make hex map scrollable

### ISSUE THREAD

**Issue by damonblack** [damonblack/wormhole-js#2]
Implement handlers and underlying code to allow dragging or use of arrow keys to move origin of map by user.

**Comment by vanderhoop** [comment]
@damonblack Not sure if you need full drag-and-drop, but I see you're using react, and I've heard great things about dan abramov's dnd library: https://github.com/react-dnd/react-dnd

I was poking around at dnd solutions for use in remote_retro, as mute mapping will required for dnd, so if you end up liking/hating something you try, lemmeknow!
