### ISSUE TITLE
Make hex map scrollable - both by dragging with the mouse, and with the arrow keys on the keyboard.

### ISSUE THREAD

**Issue by damonblack** [damonblack/wormhole-js#4]
Implement moving the map around with arrow keys and by dragging with the mouse.

**Comment by damonblack** [comment]
Basic dragging with mouse is working. 

Still need to implement arrow key controls 

and prevent the default onClick event from firing after a drag (currently causing a hex to be highlighted).

**Comment by MattConrad** [comment]
These are all 3 done, it seems. I don't want to close issues on your project but these should be closed (or updated, if they still need work).

**Comment by damonblack** [comment]
Merged.
