### ISSUE TITLE
BUG: dragging the map also highlights hexes.

### ISSUE THREAD

**Issue by damonblack** [damonblack/wormhole-js#5]
The current mouse dragging captures the mousedown and mouseup events, but the two of them together also fire an 'onClick' event, which currently hightlights a hex. Highlighting hexes by clicking on them isn't a 'feature', just something I threw it to work with the hit tester. But it would be nice to use onClick for other things.

**Comment by MattConrad** [comment]
See fix in branch fix-drag-release-click

This is only lightly tested, I've gotta run right now.

**Comment by MattConrad** [comment]
Do you care about putting fixes on separate branches?

**Comment by damonblack** [comment]
Works like a charm. Merged.
